# Generated by Django 4.0 on 2022-01-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depiction_name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('l_w_index', models.FloatField(default=0)),
                ('area', models.FloatField(default=0)),
                ('percent_area', models.FloatField(default=0)),
                ('contour_length', models.FloatField(default=0)),
                ('length_lower_part', models.FloatField(default=0)),
                ('length_upper_part', models.FloatField(default=0)),
                ('width_left_part', models.FloatField(default=0)),
                ('width_right_part', models.FloatField(default=0)),
                ('tip_angle', models.FloatField(default=0)),
                ('MP_CM_x_offset', models.FloatField(default=0)),
                ('MP_CM_y_offset', models.FloatField(default=0)),
                ('depiction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.depiction')),
            ],
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
