# Generated by Django 4.0 on 2022-01-22 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0002_depiction_metrics_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artefact_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('affiliation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='R_Import',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.IntegerField(default=0)),
                ('depiction_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.depiction')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('pers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.person')),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(default=0)),
                ('publ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.publication')),
            ],
        ),
        migrations.AddField(
            model_name='depiction',
            name='plat_name',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.plate'),
            preserve_default=False,
        ),
    ]
