# Generated by Django 4.0 on 2022-02-02 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0003_artefact_person_r_import_publication_plate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depiction',
            old_name='plat_name',
            new_name='plat_ID',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='depiction_name',
            new_name='depiction_ID',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='publ_name',
            new_name='publ_ID',
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='pers_name',
            new_name='pers_ID',
        ),
        migrations.AddField(
            model_name='plate',
            name='figure_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plate',
            name='pers_ID',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.person'),
        ),
        migrations.AddField(
            model_name='publication',
            name='ISBN',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='issue',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='publication',
            name='journal',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='depiction_name',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='pub_date',
            field=models.DateTimeField(default=0, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='person',
            name='affiliation',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='subtitle',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.CreateModel(
            name='Retouch_Depiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default=0, max_length=200)),
                ('depi_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.depiction')),
                ('pers_ID', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.person')),
            ],
        ),
        migrations.CreateModel(
            name='Retouch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retouch_name', models.CharField(default=0, max_length=200)),
                ('length', models.FloatField(default=0, max_length=200)),
                ('location', models.CharField(default=0, max_length=200)),
                ('rede_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outline.retouch_depiction')),
            ],
        ),
    ]
