# Generated by Django 4.0 on 2022-02-04 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0004_rename_plat_name_depiction_plat_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artefact',
            old_name='artefact_name',
            new_name='arte',
        ),
        migrations.RenameField(
            model_name='metrics',
            old_name='depiction_ID',
            new_name='depi',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='pers_ID',
            new_name='pers',
        ),
        migrations.RenameField(
            model_name='r_import',
            old_name='depiction_name',
            new_name='depi',
        ),
        migrations.RenameField(
            model_name='retouch',
            old_name='rede_ID',
            new_name='rede',
        ),
        migrations.RenameField(
            model_name='retouch_depiction',
            old_name='depi_ID',
            new_name='depi',
        ),
        migrations.RenameField(
            model_name='retouch_depiction',
            old_name='pers_ID',
            new_name='pers',
        ),
        migrations.RemoveField(
            model_name='depiction',
            name='plat_ID',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='publ_ID',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='pers_ID',
        ),
        migrations.AddField(
            model_name='depiction',
            name='arte',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.artefact'),
        ),
        migrations.AddField(
            model_name='depiction',
            name='outline',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='depiction',
            name='plates',
            field=models.ManyToManyField(to='outline.Plate'),
        ),
        migrations.AddField(
            model_name='plate',
            name='publications',
            field=models.ManyToManyField(to='outline.Publication'),
        ),
        migrations.AddField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(to='outline.Person'),
        ),
    ]
