# Generated by Django 4.0 on 2022-02-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0005_rename_artefact_name_artefact_arte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=0, max_length=20)),
                ('password', models.CharField(default=0, max_length=20)),
                ('firstname', models.CharField(default=0, max_length=20)),
                ('surname', models.CharField(default=0, max_length=20)),
                ('title', models.CharField(default=0, max_length=20)),
            ],
        ),
    ]
