# Generated by Django 4.0 on 2022-02-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
