# Generated by Django 4.0 on 2022-02-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0007_rename_user_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='Registration',
        ),
    ]
