# Generated by Django 4.0 on 2022-02-07 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0008_rename_users_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='arte_img',
            field=models.ImageField(default=0, upload_to=None),
        ),
        migrations.AddField(
            model_name='depiction',
            name='depi_img',
            field=models.ImageField(default=0, upload_to=None),
        ),
        migrations.AddField(
            model_name='plate',
            name='plat_img',
            field=models.ImageField(default=0, upload_to=None),
        ),
        migrations.AddField(
            model_name='retouch_depiction',
            name='rede_img',
            field=models.ImageField(default=0, upload_to=None),
        ),
    ]
