# Generated by Django 4.0 on 2022-02-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0010_userprofileinfo_delete_registration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=200)),
                ('surname', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('affiliation', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='plate',
            name='figure_number',
        ),
        migrations.RemoveField(
            model_name='plate',
            name='pers',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='people',
        ),
        migrations.RemoveField(
            model_name='retouch_depiction',
            name='pers',
        ),
        migrations.AddField(
            model_name='artefact',
            name='classification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artefact',
            name='rawmaterial',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artefact',
            name='type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plate',
            name='depictiontype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plate',
            name='figurenumber',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='depiction',
            name='arte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='outline.artefact'),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='depi_img',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='depiction_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='outline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='depiction',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='MP_CM_x_offset',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='MP_CM_y_offset',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='contour_length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='l_w_index',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='length',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='length_lower_part',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='length_upper_part',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='percent_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='tip_angle',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='width',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='width_left_part',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metrics',
            name='width_right_part',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='page',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='plate',
            name='plat_img',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='publication',
            name='ISBN',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issue',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publisher',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='r_import',
            name='cluster',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='retouch',
            name='length',
            field=models.FloatField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='retouch',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='retouch',
            name='retouch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='retouch_depiction',
            name='rede_img',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='retouch_depiction',
            name='version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='plate',
            name='creator',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.creator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publication',
            name='Authors',
            field=models.ManyToManyField(to='outline.Creator'),
        ),
        migrations.AddField(
            model_name='retouch_depiction',
            name='creator',
            field=models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.CASCADE, to='outline.creator'),
            preserve_default=False,
        ),
    ]
