# Generated by Django 4.0 on 2022-02-13 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outline', '0011_creator_remove_plate_figure_number_remove_plate_pers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creator',
            new_name='Person',
        ),
        migrations.RenameField(
            model_name='plate',
            old_name='creator',
            new_name='person',
        ),
        migrations.RenameField(
            model_name='retouch_depiction',
            old_name='creator',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='Authors',
        ),
        migrations.AddField(
            model_name='publication',
            name='people',
            field=models.ManyToManyField(to='outline.Person'),
        ),
    ]
